#!/bin/bash

git reset --hard ${{ env.LAST_COMMIT_SHA }}^
git push -f

IS_VERSION_UPDATE_COMMIT_COMPLETED=false
echo "IS_VERSION_UPDATE_COMMIT_COMPLETED=$IS_VERSION_UPDATE_COMMIT_COMPLETED" >> $GITHUB_ENV
