name: Delete Package on Feature Branch Deletion

on:
  delete:
    branches:
      - "**"

jobs:
  delete_package:
    runs-on: ubuntu-latest
    steps:
      - name: Get Organization and Package Name
        run: |
          echo "ORGANIZATION=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "PACKAGE_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

      - name: Extract branch name and prepare version tag
        run: |
          echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          VERSION_TAG="*-${GITHUB_REF#refs/heads/}"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: Delete package version associated with branch
        run: |
          PACKAGE_VERSIONS=$(curl -X GET "https://api.github.com/orgs/$ORGANIZATION/packages/npm/$PACKAGE_NAME/versions" \
            -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            | jq -r --arg VERSION_TAG "$VERSION_TAG" '.[] | select(.name | test($VERSION_TAG)) | .id')

          for VERSION_ID in $PACKAGE_VERSIONS; do
            if [ ! -z "$VERSION_ID" ]; then
              echo "Deleting package version ID: $VERSION_ID"
              curl -X DELETE "https://api.github.com/orgs/$ORGANIZATION/packages/npm/$PACKAGE_NAME/versions/$VERSION_ID" \
                -H "Authorization: bearer ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json"
            else
              echo "No matching versions found for branch $BRANCH_NAME."
            fi
          done
