name: Lint Check

on:
  pull_request:
    types: [opened, synchronize]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN_GLOBAL_O4B }}

jobs:
  check-lint-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check if lint script exists
        run: |
          if npm run --json | grep -q '"lint":'; then
            echo "Lint script exists."
            echo "RUN_LINT=true" >> $GITHUB_ENV
          else
            echo "::warning title=No Linter::Lint script does not exist. Skipping lint step."
            exit 0
          fi

      - name: Set up Node.js
        if: env.RUN_LINT == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Remove package-lock.json
        if: env.RUN_LINT == 'true'
        run: rm -f package-lock.json

      - name: Update packages to use latest "@neusta-integrate/formatter-..."
        if: env.RUN_LINT == 'true'
        run: |
          jq '(
            if .dependencies then .dependencies |= with_entries(
              if .key | test("@neusta-integrate/formatter-") then .value = "latest" else . end
            ) else . end
          ) | (
            if .devDependencies then .devDependencies |= with_entries(
              if .key | test("@neusta-integrate/formatter-") then .value = "latest" else . end
            ) else . end
          )' package.json > temp.json && mv temp.json package.json


      - name: Install dependencies
        if: env.RUN_LINT == 'true'
        run: npm install --ignore-scripts

      - name: Run Linter
        if: env.RUN_LINT == 'true'
        run: npm run lint
