name: Publish Semantic Release

on:
  push:
    paths-ignore:
      - "package.json"
      - ".github/workflows/**"
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN_GLOBAL_O4B }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{secrets.O4B_GITHUB_ACTIONS_BOT}}

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm clean-install --ignore-scripts

      - name: Read the Current Version Number
        run: |
          chmod +x ./scripts/read-current-version.sh
          ./scripts/read-current-version.sh

      - name: Determine the New Version Number
        run: |
          chmod +x ./scripts/determine-new-version.sh
          ./scripts/determine-new-version.sh

      - name: Commit Update Version
        if: env.NEW_VERSION != '' && env.NEW_VERSION != env.CURRENT_VERSION
        run: |
          chmod +x ./scripts/commit-update-version.sh
          ./scripts/commit-update-version.sh

      - name: Semantic Release
        if: github.ref == 'refs/heads/main' && env.NEW_VERSION != '' && success()
        run: |
          chmod +x ./scripts/semantic-release.sh
          ./scripts/semantic-release.sh

      - name: Delete existing package version
        run: |
          chmod +x ./scripts/delete-package-version.sh
          ./scripts/delete-package-version.sh

      - name: Publish Package
        if: env.NEW_VERSION != '' && success()
        run: |
          chmod +x ./scripts/publish-package.sh
          ./scripts/publish-package.sh

      - name: Revert "Publish Package" on Failure
        if: env.NEW_VERSION != '' && failure() && env.IS_PUBLISH_COMLETED
        run: |
          chmod +x ./scripts/revert-publish-package.sh
          ./scripts/revert-publish-package.sh

      - name: Revert "Semantic Release" on Failure
        if: github.ref == 'refs/heads/main' && env.NEW_VERSION != '' && failure() && env.IS_SEMANTIC_RELEASE_COMLETED
        run: |
          chmod +x ./scripts/revert-semantic-release.sh
          ./scripts/revert-semantic-release.sh

      - name: Revert "Commit update version" on Failure
        if: env.NEW_VERSION != '' && failure() && env.IS_VERSION_UPDATE_COMMIT_COMPLETED
        run: |
          chmod +x ./scripts/revert-commit-update-version.sh
          ./scripts/revert-commit-update-version.sh
