name: Publish Semantic Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'package.json'
  workflow_dispatch:

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN_ORGANISATION_O4B }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{secrets.O4B_GITHUB_ACTIONS_BOT}}

      - name: Set up Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm clean-install --ignore-scripts

      - name: Determine the New Version Number
        run: |
          NEW_VERSION=$(npx semantic-release --dry-run | grep 'next release version is' | sed 's/.*is //')
          echo "New version number: $NEW_VERSION"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV

          if [ -z "$NEW_VERSION" ]; then
            echo "No new version number determined, exiting workflow."
            exit 1
          fi

      - name: Read the Current Version Number
        run: |
          CURRENT_VERSION=$(jq -r '.version' package.json)
          echo "Current version number: $CURRENT_VERSION"
          echo "CURRENT_VERSION=$CURRENT_VERSION" >> $GITHUB_ENV

      - name: Commit Update Version
        if: env.NEW_VERSION != env.CURRENT_VERSION
        run: |
          jq '.version="'$NEW_VERSION'"' package.json > temp.json && mv temp.json package.json
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add package.json
          git commit -m "chore: update version to $NEW_VERSION"
          git push
          echo "LAST_COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "IS_VERSION_UPDATE_COMMIT_COMLETED=true" >> $GITHUB_ENV

      - name: Semantic Release
        if: success()
        run: |
          npx semantic-release
          echo "IS_SEMANTIC_RELEASE_COMLETED=true" >> $GITHUB_ENV

      - name: Publish
        if: success()
        run: |
          npm run publish-release
          echo "IS_PUBLISH_COMLETED=true" >> $GITHUB_ENV

      - name: Revert "Publish" on Failure
        if: failure() && env.IS_PUBLISH_COMLETED
        run: |
          RELEASE_ID=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ env.VERSION }}" \
            | jq -r '.id')
          if [ "$RELEASE_ID" != "null" ]; then
            curl -s -X DELETE -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/releases/$RELEASE_ID"
          fi

      - name: Revert "Semantic Release" on Failure
        if: failure() && env.IS_SEMANTIC_RELEASE_COMLETED
        run: |
          git push --delete origin v${{ env.VERSION }}
          git tag -d v${{ env.VERSION }}

      - name: Revert "Commit update version" on Failure
        if: failure() && env.IS_VERSION_UPDATE_COMMIT_COMLETED
        run: |
          git reset --hard ${{ env.LAST_COMMIT_SHA }}^
          git push -f
