name: Publish to GitHub Registry

on:
  push:
    branches:
      - main
      
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: npm install
    - name: Run commit analyzer and update package.json
      run: |
        VERSION=$(npx semantic-release --dry-run | grep 'The next release version is' | sed 's/.*is //')
        jq '.version="'$VERSION'"' package.json > temp.json && mv temp.json package.json
    - name: Commit package.json
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json
        git commit -m "chore: update version to $VERSION"
        git push
    - name: Semantic Release
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release
